kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-journalforing-q2
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: BREVBAKER_URL
      value: https://pensjon-brevbaker.dev.intern.nav.no
    - name: BREVSENDING_URL
      value: https://dokdistfordeling-q2.dev.intern.nav.no/rest/v1/distribuerjournalpost
    - name: JOURNALFORING_URL
      value: https://dokarkiv-q2.dev.intern.nav.no/rest/journalpostapi/v1/journalpost
  image: {{ image }}
  ingresses:
    - https://pensjon-opptjening-journalforing-q2.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi