package no.nav.pensjon.opptjening.pensjonopptjeningjournalforing.client.dokdistfordeling

import com.github.tomakehurst.wiremock.client.WireMock.*
import com.github.tomakehurst.wiremock.junit5.WireMockTest
import no.nav.pensjon.opptjening.pensjonopptjeningjournalforing.MockTokenConfig
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.http.HttpHeaders
import org.springframework.kafka.test.context.EmbeddedKafka
import org.springframework.test.annotation.DirtiesContext

@SpringBootTest
@WireMockTest(httpPort = 4567)
@DirtiesContext
@EmbeddedKafka(partitions = 1, topics = ["pensjonopptjening.pgi-endring-topic"])
internal class DokDistClientTest {

    @Autowired
    private lateinit var dokDistClient: DokDistClient

    @Test
    fun `should call dokdist with example json generated by dokDist`() {
        stubFor(
            post(urlEqualTo("/"))
                .willReturn(ok("assds"))
        )

        val request = DokDistRequest(
            journalpostId = "343752389",
            bestillendeFagsystem = "SYM",
            batchId = "54321",
            adresse = Adresse(
                adressetype = Adressetype.norskPostadresse,
                postnummer = "0505",
                poststed = "Oslo",
                adresselinje1 = "Eksempelveien 11B",
                adresselinje2 = "Bolignummer H0101",
                adresselinje3 = "Adresselinje3",
                land = "NO"),
            dokumentProdApp = "ELIN_STANDARD",
            distribusjonstype = Distribusjonstype.VEDTAK,
            distribusjonstidspunkt = Distribusjonstidspunkt.UMIDDELBART

        )
        dokDistClient.distribuerBrev(request)

        verify(1, postRequestedFor(urlEqualTo("/"))
            .withHeader(HttpHeaders.AUTHORIZATION, equalTo("Bearer ${MockTokenConfig.DOKDISTFORDELING_TOKEN}"))
            .withRequestBody(equalToJson(exampleRequestGeneratedByDokdist))
        )
    }
}


private val exampleRequestGeneratedByDokdist = """
    {
      "journalpostId": "343752389",
      "batchId": "54321",
      "bestillendeFagsystem": "SYM",
      "adresse": {
        "adressetype": "norskPostadresse",
        "postnummer": "0505",
        "poststed": "Oslo",
        "adresselinje1": "Eksempelveien 11B",
        "adresselinje2": "Bolignummer H0101",
        "adresselinje3": "Adresselinje3",
        "land": "NO"
      },
      "dokumentProdApp": "ELIN_STANDARD",
      "distribusjonstype": "VEDTAK",
      "distribusjonstidspunkt": "UMIDDELBART"
    }
"""